test: fix tests unit tests for `profile.controller.ts`  #108[wip]
cortip/isomera pull request #131
Opened 2023-12-05 13:58 UTC by naftalimurgor

### [WIP] Fix API tests after adding ORM
The tests cover pretty much what's required, the tests break due to a broken `ts-auto-mock`, what's being done: 

1. Do away with `ts-auto-mock` and use a package like `jest-mock` to offer better mocking
2. Configure `jest-mock` Currently using `jest.fn()` and `jest.mock(...)` to mock most modules and methods
3. Readjust tests and go from Red to green

### Why is it needed?
This PR mainly aims at resolving #108 for Fixing failing API unit tests to resolve failing Github actions.

### How to test it?
This PR is worked on as described in #108

2023-12-05 14:04 UTC, vygandas commented
@naftalimurgor , good start :) 

To fix [Prettier failed check](https://github.com/cortip/isomera/actions/runs/7101785627/job/19330784505?pr=131) just run `prettier . --write` - should do the trick 👌🏻

2023-12-05 17:14 UTC, naftalimurgor commented
> @naftalimurgor , good start :)
> 
> To fix [Prettier failed check](https://github.com/cortip/isomera/actions/runs/7101785627/job/19330784505?pr=131) just run `prettier . --write` - should do the trick 👌🏻
> 
> I also noticed the title "test: fix tests unit tests for profile.controller.ts" - are you planning to do PR for each separately?

Thanks for the pointing out the `prettier` :)

Regarding doing the tests seprately, we can do them all at once. This was just a way of making the draft PR active and to set the ball rolling on this issue

2023-12-05 22:02 UTC, vygandas commented
@naftalimurgor , oh yes, it can be all in one. I guess when the first few are done, all the rest should go easy 🙂

2023-12-07 17:10 UTC, vygandas requested changes

2023-12-07 17:10 UTC, vygandas commented on apps/api/src/auth/auth.controller.spec.ts
> +    // expect(result.password).not.toHaveProperty('password')
It is important, that the password is undefined when the user is logged in and the user object is returned back.

2023-12-07 17:10 UTC, vygandas commented on apps/api/src/auth/auth.service.spec.ts
> +    // expect(user).not.toHaveProperty('password', undefined)
It is important, that the password is undefined when the user is logged in and the user object is returned back.

2023-12-07 17:10 UTC, vygandas commented on apps/api/src/auth/auth.service.spec.ts
> +    // expect(user).not.toHaveProperty('password', undefined)
It is important, that the password is undefined when the user is logged in and the user object is returned back.

2023-12-07 17:10 UTC, vygandas commented on apps/api/src/auth/auth.service.spec.ts
> +    // expect(user).not.toHaveProperty('password', undefined)
It is important, that the password is undefined when the user is logged in and the user object is returned back.

2023-12-07 17:10 UTC, vygandas commented on apps/api/src/auth/guards/local-auth.guard.spec.ts
> +    // mock process.env.SESSION_SCRET
Please clear not needed comments

2023-12-07 17:10 UTC, vygandas commented on apps/api/src/auth/interceptors/token.interceptor.spec.ts
> +    // @todo: Refactor implementation of token.interceptor for implementation
Please provide a bit more details, because it's unclear why, what and what exactly needs to be refactored

2023-12-07 17:57 UTC, naftalimurgor commented on apps/api/src/auth/auth.controller.spec.ts
> +    // expect(result.password).not.toHaveProperty('password')
This sense, as password wouldn't be in the user object. Pushing changes to resolves this.

2023-12-07 17:59 UTC, naftalimurgor commented on apps/api/src/auth/guards/local-auth.guard.spec.ts
> +    // mock process.env.SESSION_SCRET
Okay, noted.

2023-12-08 08:10 UTC, naftalimurgor commented
Hey @vygandas 
I'll push some changes and resolve most of the highlighted areas today evening. Got a term paper today :)

2023-12-08 13:34 UTC, vygandas commented
> Hey @vygandas I'll push some changes and resolve most of the highlighted areas today evening. Got a term paper today :)

Alright, no worries. Good luck with that! 😊

2023-12-09 10:04 UTC, naftalimurgor commented on apps/api/src/auth/auth.service.spec.ts
> +    // expect(user).not.toHaveProperty('password', undefined)
Hey @vygandas 
Dug deeper and realized:
This assertion: 
```javascript
expect(user).not.toHaveProperty('password', undefined)
```
is testing: user object not to haveProperty password, and not undefined. Seems like in the implementation, could the issue be with this line?:
https://github.com/cortip/isomera/blob/673678b7b052a93a8bd310408315bcfe3f2d2e7d/apps/api/src/auth/auth.controller.ts#L64

2023-12-09 15:42 UTC, naftalimurgor commented
> > Hey @vygandas I'll push some changes and resolve most of the highlighted areas today evening. Got a term paper today :)
> 
> Alright, no worries. Good luck with that! 😊

Thank you 😀

2023-12-09 18:58 UTC, vygandas commented on apps/api/src/auth/auth.service.spec.ts
> +    // expect(user).not.toHaveProperty('password', undefined)
@naftalimurgor , yeah, you are right, this should be added to separate issue :)

2023-12-09 19:47 UTC, vygandas commented
@naftalimurgor it's just prettier left 🤣 almost there...

2023-12-09 20:05 UTC, naftalimurgor commented
@vygandas 
seeing things not looking pretty, let me fix that! :)

2023-12-09 20:26 UTC, vygandas approved these changes
👌🏻

2023-12-09 20:26 UTC, merged

2023-12-09 20:27 UTC, naftalimurgor commented
Awesome!