Feature/2 fa
cortip/isomera pull request #213
Opened 2024-02-06 10:08 UTC by PhamAnhHoang

### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2024-02-07 20:04 UTC, vygandas commented on apps/platform/src/hooks/verify2FAHook.ts
> +  onSuccess?: (response: any) => void
Maybe it's a good place for DTO?

2024-02-10 14:10 UTC, vygandas requested changes
Also, missing recovery codes which should have been displayed when 2fa was confirmed.
When trying to login, get error:
```
[Nest] 74169  - 02/10/2024, 4:08:17 PM   ERROR [ExceptionsHandler] The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
    at new NodeError (node:internal/errors:405:5)
    at Function.from (node:buffer:333:9)
    at new Buffer (node:buffer:288:17)
    at Object.exports.decode (/Users/vygandas/git/isomera/node_modules/thirty-two/lib/thirty-two/thirty-two.js:87:16)
    at Object.keyDecoder (/Users/vygandas/git/isomera/node_modules/@otplib/plugin-thirty-two/index.js:17:20)
    at authenticatorDecoder (/Users/vygandas/git/isomera/node_modules/@otplib/core/index.js:413:18)
    at authenticatorCheckWithWindow (/Users/vygandas/git/isomera/node_modules/@otplib/core/index.js:423:37)
    at Authenticator.checkDelta (/Users/vygandas/git/isomera/node_modules/@otplib/core/index.js:436:12)
    at Authenticator.check (/Users/vygandas/git/isomera/node_modules/@otplib/core/index.js:358:24)
    at Authenticator.verify (/Users/vygandas/git/isomera/node_modules/@otplib/core/index.js:365:17)

```
Missing .env maybe or just a bug?

2024-02-10 14:10 UTC, vygandas commented on apps/api/src/auth/auth.controller.ts
> +    @AuthUser() user: Pure<UserEntity> & { isTwoFactorAuthenticated: boolean }
Shouldn't this prop already be in UserEntity?

2024-02-10 14:10 UTC, vygandas commented on apps/api/src/auth/auth.service.ts
> +  signToken(payload: object): {
Should be specific DTO or interface

2024-02-10 14:10 UTC, vygandas commented on apps/api/src/auth/auth.service.ts
> +  public generateAccessToken(payload: object): string {
Should be specific DTO or interface

2024-02-10 14:10 UTC, vygandas commented on apps/api/src/auth/auth.service.ts
> +  public generateRefreshToken(payload: object): string {
Should be specific DTO or interface

2024-02-17 06:07 UTC, PhamAnhHoang commented on apps/api/src/auth/auth.controller.ts
> +    @AuthUser() user: Pure<UserEntity> & { isTwoFactorAuthenticated: boolean }
This field doesn't exist in the entity because it's not being stored in the db

2024-02-23 15:24 UTC, merged