Feature/type orm configuration
cortip/isomera pull request #23
Opened 2022-10-28 14:30 UTC by CristoferPortela

typeorm basic configurations added

2022-10-28 14:57 UTC, vygandas requested changes

2022-10-28 14:57 UTC, vygandas commented on apps/api/src/app/app.module.ts
> +import {TerminusModule} from '@nestjs/terminus';
How come there're no spaces after { and before } but prettier still passed 🧐 It should be formatted as everything else in the code. Can it be a configuration issue?

2022-10-28 14:57 UTC, vygandas commented on apps/api/src/app/app.module.ts
> +      ,
Why is this one here?

2022-10-28 14:57 UTC, vygandas commented on apps/api/src/config/database.ts
> +  type: process.env.TYPEORM_DRIVER as never,
`never` shouldn't be used here. Especially when there's a specific interface `PostgresConnectionOptions` used which has only one type variant. Should be either an appropriate interface used or multiple interfaces with `|`

2022-10-28 14:57 UTC, vygandas commented on apps/api/src/config/datasource.ts
> +import dotenv from 'dotenv';
Maybe Datasource can import configuration from the database config? We should avoid duplicated code.

2022-10-28 14:57 UTC, vygandas commented on package.json
> +    "mysql2": "^2.3.3",
Is it the user anywhere in the code? If it's not imported anywhere, let's remove this.

2022-10-28 15:04 UTC, CristoferPortela commented on apps/api/src/app/app.module.ts
> +import {TerminusModule} from '@nestjs/terminus';
probably my IDE had not configured the correct prettier here, I'll change it and commit

2022-10-28 15:05 UTC, vygandas commented on apps/api/src/app/app.module.ts
> +import {TerminusModule} from '@nestjs/terminus';
Also please make sure `yarn prettier` fails if it's left like that for the future :)

2022-10-28 15:07 UTC, CristoferPortela commented on apps/api/src/app/app.module.ts
> +import {TerminusModule} from '@nestjs/terminus';
The prettierc has no rule about this, I'll change that then

2022-10-28 15:47 UTC, CristoferPortela commented on apps/api/src/app/app.module.ts
> +      ,
Solved

2022-10-28 15:50 UTC, CristoferPortela commented on apps/api/src/config/database.ts
> +  type: process.env.TYPEORM_DRIVER as never,
fixed

2022-10-28 15:50 UTC, CristoferPortela commented on package.json
> +    "mysql2": "^2.3.3",
removed

2022-10-29 12:38 UTC, vygandas approved these changes
Now looks good 🙂

2022-10-29 13:10 UTC, merged